### ISSUE TITLE
Create nomal '.js' file

### ISSUE THREAD

**Issue by AppIns** [nornagon/atom#9]
You can compile the .coffee file into a .js file using CoffeeScript. You should make sure to keep both and compile to JS in every release.

**Comment by nornagon** [comment]
This isn't a library :) it's something you should copy/paste into your (CoffeeScript) game and modify. I'll update the README to indicate that.

I don't use atom any more, so I'm not planning on updating it, but I'd happily consider merging a PR to convert the coffee to nice, modern ES6 :) Unfortunately the CoffeeScript compiler's output isn't great raw material.
